### ISSUE TITLE
Design & document a sql database schema

### ISSUE THREAD

**Issue by tienyuan** [hackforla/heart#1]
### Goal 
Design & document a sql database schema based on the information architecture. 

### Desired Result 
A diagram like those [pictured here](https://www.lucidchart.com/pages/database-diagram/database-models#top-info) so we can put it into the Wiki/Discuss/Implement

### Resources/Content
Information Architecture from 11/26/18 Design Sprint is:
https://github.com/hackforla/heart/wiki/Information-Architecture

Please also review the 12/3/18 Mockup Discussion notes:
https://hackforla.slack.com/files/U9TEHKS8M/FEHVD4B33/notes_from_design_review_12_3_19.txt
- acknowledgements from the back of the original paper intake form
- electronic signature (checkbox + typed name)
- "Why are you applying to clear your record?" 
- Assume separate accounts and a login are required 
- Assume that profile notes act more like comments added by the logged in user, not a general text field
- Urgent rush / ordering needs (see below)

**Ordering Needs**
_"What happens with the urgent rush people? Would it prioritize them or allow us to sort it?"_
People should be sorted by clinic attended date except when "urgent rush", then move to top in order of urgent rush.

Aka Gina and her team may opt to prioritize certain participants because of special circumstances. For example, someone may need their record expunged to pass a background check for a job application. All urgent-rush people should be before non-urgent-rush people.

---
For the sake of our future selves/volunteers, we're trying to document the intent/thoughts/assumptions/decisions that lead up to the code. 

So this is an extra wordy issue description 😃

**Comment by jonmelvin** [comment]
[sql_script_for_heart_v1.txt](https://github.com/hackforla/heart/files/2650014/sql_script_for_heart_v1.txt)

**Comment by tienyuan** [comment]
👍 I look forward to hearing your thoughts on Monday. I'll study it a bit this weekend.

https://dataedo.com/kb/tools/ssms/create-database-diagram seems to say it's possible to generate a prettier version of the db schema so it's easier to see relationships

**Comment by jonmelvin** [comment]
Diagram from SQLServer management studio for the tables (does not include the update for having the picture in the client table - see text doc above for that).
![heart_diagram](https://user-images.githubusercontent.com/25702027/49690169-20391e80-fae1-11e8-80e7-e9ca6e7aecd3.jpg)

**Comment by tienyuan** [comment]
We discussed the database during hacknight and an updated version of the schema is in progress

**Comment by tienyuan** [comment]
FYI @mitchellwandrews @jonmelvin 

I did a quick comparison between the [IA:Intake Form](https://github.com/hackforla/heart/wiki/Information-Architecture) fields, the [IA:Profile Page](https://github.com/hackforla/heart/wiki/Information-Architecture) fields and the [designed intake form (in progress)](https://github.com/hackforla/heart/pull/18)

Mostly matches. Fields in the Intake Form exist in the Profile Page. Note, the design is missing the legal agreement fields, the electronic sig fields and implies that Clinics Attended have dates. So best to continue to go by the [Info Architecture doc](https://github.com/hackforla/heart/wiki/Information-Architecture)

**Comment by tienyuan** [comment]
Addressed in https://github.com/hackforla/heart/issues/32
