### ISSUE TITLE
Client Side Contract

### ISSUE THREAD

**Issue by abregorivas** [hackforla/heart#120]

**Comment by RGKaizen** [comment]
The strategy here is to use Typescript create interfaces for each of the endpoints on the backend. The interfaces (contracts in implementation) will tell the frontend what to expect from the backend and vice-verse.

**Comment by RGKaizen** [comment]
# Acceptance Criteria
Provide a set of interfaces that define the shape of data for and from the different endpoints, particularly participants, citations and notes.

- [ ] - Introduce typescript to the api
- [ ] - Create contract for participants
- [ ] -Create contract for citations
- [ ] -Create contract for notes
