### ISSUE TITLE
[Bug] Citations cannot submit form data to database.

### ISSUE THREAD

**Issue by serpient** [hackforla/heart#130]
# When trying to submit the form data to database:
### API Console:
![image](https://user-images.githubusercontent.com/29721784/59649279-ed7a7d80-9136-11e9-929f-4e8d7a24a07f.png)
### Request Payload
![image](https://user-images.githubusercontent.com/29721784/59649289-f79c7c00-9136-11e9-9a26-1a0deb34a200.png)
### Response 
![image](https://user-images.githubusercontent.com/29721784/59649294-fe2af380-9136-11e9-9c2d-fde40dc8958b.png)

**Comment by serpient** [comment]
### API Console:
![image](https://user-images.githubusercontent.com/29721784/59649279-ed7a7d80-9136-11e9-929f-4e8d7a24a07f.png)
### Request Payload
![image](https://user-images.githubusercontent.com/29721784/59649289-f79c7c00-9136-11e9-9a26-1a0deb34a200.png)
### Response 
![image](https://user-images.githubusercontent.com/29721784/59649294-fe2af380-9136-11e9-9c2d-fde40dc8958b.png)

**Comment by shlomibe21** [comment]
This issue was fixed and according to Tien it is ok to close it.
