### ISSUE TITLE
IntakeForm cannot submit form data to database.

### ISSUE THREAD

**Issue by serpient** [hackforla/heart#132]
# Issue: We need to know the API route to save intake form data to.

### Current Form Data 
<img width="228" alt="Screen Shot 2019-06-17 at 7 47 17 PM" src="https://user-images.githubusercontent.com/29721784/59650001-6b3f8880-9139-11e9-8226-2eb7bef927ed.png">

**Comment by tienyuan** [comment]
Currently GitRafaelZamora and jasonlev

**Comment by tienyuan** [comment]
I think this is fixed?
