### ISSUE TITLE
[Bug] Personal participant profile cannot submit form data to database

### ISSUE THREAD

**Issue by serpient** [hackforla/heart#133]
# When trying to submit the updated data
### Request
<img width="272" alt="Screen Shot 2019-06-17 at 7 54 38 PM" src="https://user-images.githubusercontent.com/29721784/59650145-cb362f00-9139-11e9-99b7-d6f3db843260.png">
### Response
<img width="442" alt="Screen Shot 2019-06-17 at 7 54 45 PM" src="https://user-images.githubusercontent.com/29721784/59650148-cffae300-9139-11e9-9044-d5b87801656f.png">

**Comment by tienyuan** [comment]
Currently kkchu791, jun-snow are working on this

**Comment by tienyuan** [comment]
Fixed
