### ISSUE TITLE
Add user name to nav and fix styling

### ISSUE THREAD

**Issue by tienyuan** [hackforla/heart#147]
For this issue, please update the navbar in all places for the following:
- [ X ] Add username to Nav
- [ X ] Apply navbar style to 'Log Out'
- [ X  ] Remove 'Intake Upload'
- [  ] Convert to Material UI Appbar
- [  ] Make the bar stick to top 
- [  ] Pull styles and add them to a useStyles hook
---

### Mockup

Please note the Mockup is inaccurate
- Ignore Intake Upload, not building it
- Ignore user avatar, not building it
- It's missing Log Out
<img width="1069" alt="example-2" src="https://user-images.githubusercontent.com/1626276/60411170-64286980-9b80-11e9-8174-82353fb94773.png">

### Master as of 6/30/19
<img width="1307" alt="current" src="https://user-images.githubusercontent.com/1626276/60411165-612d7900-9b80-11e9-810e-b9da8c4c5a4f.png">

**Comment by abregorivas** [comment]
I will Update Navbar to use Material UI to enable responsiveness on screen size change
