### ISSUE TITLE
Updating Participants' List (Index / Home page) to read from the database

### ISSUE THREAD

**Issue by mbrajeux** [hackforla/heart#149]
We want to remove the test data and update the index / homepage so that it

- [ x]  reads information directly from the database and populate the required fields for individual participants, and

- [x ]  when user presses the 'view profile' button on a specific individual's details, it takes the user to the individual's profile page so the user can view their personal information. 

As a user, when I press the view button on a participant's profile, 
I want to be able to see that participant's personal information so I can review it. 

---
Index page with 'View Profile' button
![Screenshot_070119_081337_PM](https://user-images.githubusercontent.com/24706016/60480021-d2326680-9c3c-11e9-9830-92aa993ff655.jpg)

Should take user to... 

Individual Profile Page
![Screenshot_070119_081548_PM](https://user-images.githubusercontent.com/24706016/60480064-03ab3200-9c3d-11e9-9dac-b367523c8fe2.jpg)

**Comment by thomasjinlo** [comment]
@mbrajeux In the screenshot of the participants list, the first column says `Rush`. What does that mean exactly? Does it represent the priority level for that participant?

**Comment by tienyuan** [comment]
Matt
