### ISSUE TITLE
Make the backend response return an empty array

### ISSUE THREAD

**Issue by tienyuan** [hackforla/heart#150]
When there is no value to be returned from the database,
Roland would like to get an empty array as a response.

This should be the case for all endpoints:

- [x] citations endpoints
- [x] participant endpoints
- [x] users endpoints

**Comment by shlomibe21** [comment]
From what I see there is no issue in the back-end. We always returning from the api an array and if there is no data the array is empty. Roland let's talk about it on the next meeting.

**Comment by abregorivas** [comment]
This is good! I anticipated that result once the res.data was done on each end point.
Thanks for looking into the issue
