### ISSUE TITLE
Create inputs for Intake Page

### ISSUE THREAD

**Issue by bingr001** [hackforla/heart#162]
### Overview
Create inputs to be used on the Intake page in the forms.

### Action Items

- [x] text input
- [x] radio
- [x] dropdown
- [x] checkbox
- [x] submit

### Resources/Instructions
Related to ticket #140

**Comment by bingr001** [comment]
I would like to be assigned to this. I'll try to take care of the first 3 check boxes if someone else wants to do the last two?.

**Comment by kkchu791** [comment]
I'd like to work on checkbox component.
