### ISSUE TITLE
Add columns to Participant Table for Intake Form

### ISSUE THREAD

**Issue by kkchu791** [hackforla/heart#232]
### Overview
Need to add some new columns in Participant table to account for new fields in Intake Form

### Columns
**Clinic Section**
1.clinic_date: string or date

**Agreement Section**
2. voluntary?:boolean
3. homeless?:boolean
4. agreement_1?:boolean
5. agreement_2?:boolean
6. agreement_3?:boolean
7: agreement_4?:boolean
8: agreement_5?:boolean
9: agreement_6?:boolean
10:contact_by_phone: boolean
11:contact_by_email: boolean

**Program Info Section (most are booleans)**
12. completed_service_hours?
13: service_hours? integer
14. completed_community_obligations?
15. mental_health_provider?
16. physical_health_provider?
17. dental_health_provider?
18. substance_abuse_resources?
19. vaccination?
20. sti/std_testing?
21. first_aid_training?
22. housing_case_management?
23. emergency_housing?
24. safe_park_la?
25. veterans_housing_resources?
26. housing_survey?
27. financial_assistance?
28. calfresh?
29. MediCal_insurance?
30. department_of_consumer_and_business_affairs?
31. voter_registration?
32. birth_certificate?
33. veterans_services?
34. library_card?
35. dmv?
36. capp?
37. haircut?
38. shower_or_hygiene_kit?
39. health_screening?
40. cell_phone?
41. opened_an_email_account?
42. public_defender?
43. legal_aid?
44. medication?
45. domestic_violence_resources?
46. child_support_resources?
47. victims_assistance_program?
48. probation_resources?
49. job_training?
50. family_source_center_services?

@tienyuan 

Not positive how much of the form is subject to change, but these columns are needed based on the current mockup.

![Screen Shot 2019-08-13 at 12 05 33 PM](https://user-images.githubusercontent.com/11531186/62972864-dc15c080-bdc9-11e9-9be0-83bd980ad648.png)
![Screen Shot 2019-08-13 at 12 05 15 PM](https://user-images.githubusercontent.com/11531186/62972865-dddf8400-bdc9-11e9-8bc1-6bbf5872870b.png)
![Screen Shot 2019-08-13 at 12 05 47 PM](https://user-images.githubusercontent.com/11531186/62972869-e041de00-bdc9-11e9-83f6-0b3b456df3b5.png)
![Screen Shot 2019-08-13 at 12 05 25 PM](https://user-images.githubusercontent.com/11531186/62972871-e041de00-bdc9-11e9-8bda-298948351a88.png)

**Comment by tienyuan** [comment]
@kkchu791 thank you so much for taking a look through all the fields!

**Comment by tienyuan** [comment]
Alright, I used different names...

```
  id
  agreement_voluntary BOOLEAN,
  agreement_at_risk BOOLEAN,
  agreement_obligations BOOLEAN,
  agreement_infractions BOOLEAN,
  agreement_warrants BOOLEAN,
  agreement_court_form BOOLEAN,
  agreement_progress BOOLEAN,
  agreement_phone_contact BOOLEAN,
  agreement_email_contact BOOLEAN,
  obligations_hours_complete BOOLEAN,
  obligations_hours SMALLINT,
  obligations_complete BOOLEAN,
  health_mental BOOLEAN,
  health_physical BOOLEAN,
  health_dental BOOLEAN,
  heath_substance_abuse BOOLEAN,
  health_vaccination BOOLEAN,
  health_sti_std BOOLEAN,
  health_first_aid BOOLEAN,
  housing_case_management BOOLEAN,
  housing_emergency BOOLEAN,
  housing_safeparkla BOOLEAN,
  housing_veterans BOOLEAN,
  housing_survey BOOLEAN,
  government_fin_assistance BOOLEAN,
  government_calfresh BOOLEAN,
  government_medi_cal BOOLEAN,
  government_dept_consumer BOOLEAN,
  government_voter BOOLEAN,
  government_birth BOOLEAN,
  government_vet_services BOOLEAN,
  government_library BOOLEAN,
  government_dmv BOOLEAN,
  government_capp BOOLEAN,
  hygiene_haircut BOOLEAN,
  hygiene_shower_kit BOOLEAN,
  hygiene_screening BOOLEAN,
  communication_cell BOOLEAN,
  communication_email BOOLEAN,
  legal_public_defender BOOLEAN,
  legal_legal_aid BOOLEAN,
  legal_medication BOOLEAN,
  legal_domestic BOOLEAN,
  legal_child_support BOOLEAN,
  legal_victim BOOLEAN,
  legal_probation BOOLEAN,
  employment_training BOOLEAN,
  family_source_center BOOLEAN,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  participant_id INTEGER
```

Any opinions?
