### ISSUE TITLE
Explore framework options for main profile app

### ISSUE THREAD

**Issue by tienyuan** [hackforla/heart#3]
### Goal 
**To vet a possible framework for the 'main profile app' to store participant profile info at the office.** Note that we will need authentication, this is a CRUD app and we're leaning towards using a sql db.

Possible frameworks are:
- Python: Flask
  - https://medium.com/@aliciagilbert.itsimplified/a-slick-crud-application-built-using-python-with-flask-and-sqlite3-to-teach-simple-mysql-queries-bd75e1109582
- Python: Django 
  - https://www.zeolearn.com/magazine/building-a-crud-application-using-python-and-django
- NodeJS: Express
  - https://medium.com/@vsvaibhav2016/create-crud-application-in-express-js-9b88a5a94299
- NodeJS: Keystone
  - wesrowe tried it, defaults to mongodb 
  - https://keystonejs.com/
- Ruby: Sinatra
  - https://github.com/shannonjen/sinatra_crud_tutorial
- Ruby: Ruby on Rails
  - https://medium.com/@nancydo7/ruby-on-rails-crud-tutorial-899117710c7a
- or go with something else you'd vote for!

### Desired Result
Pick a possible framework and try it out.  Then write down your thoughts/opinions/notes for the potential framework. 

_Code/prototypes produced should be used to form your opinions. Demos are nice to have, not required_

Examples of what to include:
- "I really liked bleh bleh, but it was hard to blah blah"
- Pros (what was good, reasons to do it, likes)
- Cons (what was hard, reasons to skip it, dislikes)
- Did this inspire another idea/approach?
- Can I hook up a sql db? 👍/ 👎
- Can I make a tiny CRUD form? 👍/ 👎
- Is this possible? 👍/ 👎
- Is this time consuming/super hard? 👍/ 👎
- Is it worth the effort? 👍/ 👎

### Background
**Assumptions**
We'll be able to use what we want as the database.
We'll want to write tests.

**Hypothesis**
We should go with Python, NodeJS or Ruby as the main backend language because we think many developers coming to Hack for LA will know one of them. 

---
For the sake of our future selves/volunteers, we're trying to document the intent/thoughts/assumptions/decisions that lead up to the code. 

So this is an extra wordy issue description 😃

**Comment by mitchellwandrews** [comment]
I'll put together something this weekend using node/express and JWT for authentication. Definitely my prefered framework as I have had a lot of experience with it, but I also know python/flask/django and I'm sure I could learn Keystone.

**Comment by tienyuan** [comment]
Very cool @mitchellwandrews ! Yes, it'd definitely be valuable to get your thoughts on how well express might fit this project.

**Comment by tienyuan** [comment]
I'm trying out https://sailsjs.com/

**Comment by jonmelvin** [comment]
Is Sails what you would recommend I look at?  
(Work got busy, so it will be slower going than last week - sorry.)

Jon Melvin


PS - did you see the database scripts?  They are from my CSharp project.  For the nodejs: I put the table creation right in the nodejs app I created so that there are not separate modules to keep in synch - a nice approach for small apps.

**Comment by tienyuan** [comment]
@jonmelvin  Choose whatever catches your eye. 

If you chose a different framework, we'd have more to compare next Monday. 
If you overlap, we'd have another perspective. All good :-)

If you favor nodejs, some newer frameworks I haven't mentioned already are: 
- https://nextjs.org/
- https://feathersjs.com/
- https://github.com/koajs

Found them in https://2018.stateofjs.com/back-end-frameworks/overview/

Or one of the python or ruby ones I mentioned in the original description.

Freetime changes alot, at least for me! So let's work to pick something developer-friendly, so we can make the most of our time!

**Comment by mitchellwandrews** [comment]
@tienyuan I have heard good things about koajs but I haven't used it yet. Might try that instead of express since I already have a good feel for express.

**Comment by tienyuan** [comment]
@mitchellwandrews nice! Yes, if you already know the pros and cons of express, totally try Koa. It would be nice to see how it compares. Maybe it'll reaffirm the argument for express ¯\_(ツ)_/¯

**Comment by tienyuan** [comment]
Sails.JS - Started an app, put it into a docker container, hooked up postgres, added new model/controller, stopped when adding a view

- Pros: So starting an application was easy, it has a MVC structure and files are organized well. 
- Cons: But the docs are poor and the community around it seems to be slowing down. Most articles I found were written for an earlier version.
- Can I hook up a sql db? 👍Yes, hooking up a db was very easy
- Can I make a tiny CRUD form? 👍Yes, I made the model/controller with the generator with no trouble, but went down a rabbit hole when I realized I needed to learn vue to add a page.
- Is this possible to use this? 👎Probably but I wouldn’t vote for it due to poor docs/community
- Is this time consuming/super hard? 👎Backend is fast to build with
- Is it worth the effort? 👎Probably not unless we only want to use it as a backend
I'll try something else if I've got time today

**Comment by mitchellwandrews** [comment]
KoaJS - Built a simple crud app for notes, hooked up to mysql on AWS RDS with Knex.js query builder. 

- Pros: very lightweight minimalist framework, built by the team behind express.js
- Cons: Decent documentation, but I feel that express has better documentation
- Can I hook up a sql db? 👍 yes, super easy
- Can I make a tiny crud form 👍 yes, routing is very friendly to es6 syntax
- Is this possible to use this? 👍 yes, but would rather use express because of better docs/familiarity 
- Is this time consuming/super hard? 👎 no built to be very lightweight and easy to use
- Is it worth the effort? 👍 Yes, would be some initial learning curve but seems to be lightweight and good for building api's fast

**Comment by tienyuan** [comment]
We've decided on Express serving backend and frontend pages. Pages will use react components and the database is Postgres.
