### ISSUE TITLE
Be able to see a list of profiles/homepage

### ISSUE THREAD

**Issue by calexity** [hackforla/heart#35]
As Gina and team
When I want to see profiles for our participants
Then I can see a list of them.

*Notes*
- List oldest at top to newest based on clinic attended
- No search or sorting

*Design*
https://invis.io/MNPV2LSU4ZE#/339673550_ProfileIndex_Large

**Comment by mitchellwandrews** [comment]
the api route is done for this /participants

**Comment by abregorivas** [comment]
List has been added but still pending the following:
- List oldest at top to newest based on clinic attended (need more real records to flush out)
- Determine if there is more functionality needed on the list e.g (sorts, filters, highlights, alerts...)
