### ISSUE TITLE
Be able to view/edit an individual profile

### ISSUE THREAD

**Issue by calexity** [hackforla/heart#36]
As Gina
When I want to work on a file
Then I want to be able to get more info on that individual 
So I can work to get rid of their tickets. Cool!

*Notes*
- Be able to view profile
- Be able to edit and save basic profile info
- Be able to see and change status

**Comment by mitchellwandrews** [comment]
@serpient the api route is done for this /participants/:id

**Comment by abregorivas** [comment]
This issue is closed because the profile info will be updated in the intake form.
