### ISSUE TITLE
Sails / Docker install on windows

### ISSUE THREAD

**Issue by jonmelvin** [hackforla/heart#5]
Configuring Sails app in docker, on Windows.  Am getting:

sails_1     | No `sails.config.custom.stripeSecret` was configured.
sails_1     | No `sails.config.custom.stripePublishableKey` was configured.
sails_1     | No `sails.config.custom.mailgunSecret` was configured.
sails_1     | No `sails.config.custom.mailgunDomain` was configured.
sails_1     |
sails_1     | Until this is addressed, this app's billing and email features
sails_1     | will be disabled and/or hidden in the UI.
sails_1     |
sails_1     |  [?] If you're unsure or need advice, come by https://sailsjs.com/support
sails_1     | ---------------------------------------------------------------------
sails_1     | verbo: custom hook loaded successfully. (1ms)
sails_1     | verbo: Starting app at /app...
sails_1     | verbo: Running the setup logic in `sails.config.bootstrap(done)`...
sails_1     | error: Bootstrap encountered an error: (see below)
sails_1     | verbo: Lowering sails...
sails_1     | error:
sails_1     | error: TypeError: Cannot read property 'readJson' of undefined
sails_1     |     at Object.module.exports.bootstrap (/app/config/bootstrap.js:40:55)
sails_1     |     at /usr/local/lib/node_modules/sails/lib/app/private/bootstrap.js:73:34
sails_1     |     at Sails.runBootstrap (/usr/local/lib/node_modules/sails/lib/app/private/bootstrap.js:97:5)
sails_1     |     at Sails.wrapper [as runBootstrap] (/usr/local/lib/node_modules/sails/node_modules/@sailshq/lodash/lib/index.js:3275:19)
sails_1     |     at Sails.initialize (/usr/local/lib/node_modules/sails/lib/app/private/initialize.js:67:9)
sails_1     |     at Sails.wrapper [as initialize] (/usr/local/lib/node_modules/sails/node_modules/@sailshq/lodash/lib/index.js:3275:19)
sails_1     |     at /usr/local/lib/node_modules/sails/lib/app/lift.js:63:13
sails_1     |     at /usr/local/lib/node_modules/sails/node_modules/async/dist/async.js:3853:24
sails_1     |     at replenish (/usr/local/lib/node_modules/sails/node_modules/async/dist/async.js:946:17)
sails_1     |     at iterateeCallback (/usr/local/lib/node_modules/sails/node_modules/async/dist/async.js:931:17)
sails_1     |     at /usr/local/lib/node_modules/sails/node_modules/async/dist/async.js:906:16
sails_1     |     at /usr/local/lib/node_modules/sails/node_modules/async/dist/async.js:3858:13
sails_1     |     at /usr/local/lib/node_modules/sails/lib/app/load.js:278:13
sails_1     |     at /usr/local/lib/node_modules/sails/node_modules/async/dist/async.js:421:16
sails_1     |     at processQueue (/usr/local/lib/node_modules/sails/node_modules/async/dist/async.js:1565:20)
sails_1     |     at taskComplete (/usr/local/lib/node_modules/sails/node_modules/async/dist/async.js:1588:9)
sails_1     |
sails_1     | error: Could not load Sails app.
sails_1     | error:
sails_1     | error: Tips:
sails_1     | error:  • First, take a look at the error message above.
sails_1     | error:  • Make sure you've installed dependencies with `npm install`.
sails_1     | error:  • Check that this app was built for a compatible version of Sails.
sails_1     | error:  • Have a question or need help?  (http://sailsjs.com/support)
main-app-sails_sails_1 exited with code 1

**Comment by tienyuan** [comment]
We're not using sails so closing this
