### ISSUE TITLE
Update Profile design with feedback from 12/3 and any changes needed due to form

### ISSUE THREAD

**Issue by calexity** [hackforla/heart#8]

**Comment by mbrajeux** [comment]
Response from Gina regarding the 'status progress' in relation to either citations or violations (one citation will generally contain multiple violations, each participant can have multiple citations and is referred to as one 'case', for each case the team sends one motion per citation but they can come back at different times => at the moment, status is only upgraded when all citations have been received back, 

Two possible solutions depending on feasibility / interface overload: 

1. only have status progress relating to each individual case / profile page (ie multiple citations)
2. include status progress for each individual citation / motion sent 

Gina is ok with both options (she initially described option 1 as their current process, but agreed option 2 would be "very useful" if feasible) - see below for initial response. 

> Each citation is handled as one case - all the vios are dismissed at once. 
> The status will pertain to the person and be a summary of what’s going on. We won’t close someone out until all their citations have been processed.  For example, a person who has had some citations dismissed but not all will be “motions sent.” Once the final citation is back from court they will be “closed complete- citations dismissed”

**Comment by mbrajeux** [comment]
Additional request for Gina regarding the MVP - is it manageable for now? 

Can you also add in a check box for the user to confirm what background checks have been run? It could just be a list of tick boxes:
CCHRS
W&W
DMV
TCIS

**Comment by mbrajeux** [comment]
CCHRS - Consolidated Criminal History Reporting System
W&W - ?
DMV - Department of Motor Vehicles
TCIS - Trial Court Information System
