### ISSUE TITLE
Upload CSV page

### ISSUE THREAD

**Issue by charlottesauce** [hackforla/heart#85]
As Gina,
I want to be able to upload and preview CSV Files
so that I know that the CSV file is the proper one and don't import the wrong data.

Data points to be shown in this order:
- Timestamp
- Clinic/Date 
- Last Name
- First Name
- Gender
- DOB
- DL 
- Phone
- Email
- Address

Consider:
- Error state when uploading a non-csv file
- Empty fields
- How to confirm upload of file

Page states to design:
1. Empty State
2. Preview State
3. Error state? (fields don't match up or ??? field) 
4. Submitted State

**Comment by drduong4** [comment]
https://invis.io/MNPV2LSU4ZE#/360678451_Import_CSV_Form
