### ISSUE TITLE
Build a docker container with postgres

### ISSUE THREAD

**Issue by tienyuan** [hackforla/heart#9]
Since we've decided to use Postgres (#3), we want to make it easy to spin up a consistent postgres database for local development

- [x] Make a Dockerfile for spinning up Postgres 10.6
- [x] Postgres container should expose port
- [x] Write docs on how to setup and use pgadmin with the container

We've also discussed setting up a little hosted test db for shared use

**Comment by thekaveman** [comment]
Hey @mitchellwandrews! Take a look at #20 - does this seem like a good starting point?

**Comment by mitchellwandrews** [comment]
@thekaveman Looks like a good starting point! I'm planning on adding another container for our main app.

**Comment by tienyuan** [comment]
@thekaveman covered it all ! 

Closing...
